name: Autograding Tests
'on':
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Evaluation
      id: evaluation
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Evaluation
        setup-command: npm install
        command: node ./test/index.js
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        EVALUATION_RESULTS: "${{steps.evaluation.outputs.result}}"
      with:
        runners: evaluation
